version: "3.8"
services:
  api-server:
    build:
      context: .
    environment:
      - RAILS_ENV=development
      - BUNDLE_DEPLOYMENT=0
      - BUNDLE_WITHOUT=production:development
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./app
          target: /rails/app
        - action: rebuild
          path: ./public
        - action: rebuild
          path: ./config
        - action: rebuild
          path: ./db
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./Gemfile
  database:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
