on:
  push:
    branches: [feature/deploy_production_settings]
jobs:
  deploy:
    name: deploy workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          export_environment_variables: false
      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "asia-northeast1-docker.pkg.dev"
      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: asia-northeast1
          image: asia-northeast1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}
          secrets: |
            RAILS_MASTER_KEY=RAILS_MASTER_KEY:latest
            DATABASE_URL=DATABASE_URL:latest
          project_id: ${{ vars.GCP_PROJECT_ID }}
          flags: "--allow-unauthenticated --port=3000"

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
